### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by craigacronin**
Hi Warren,

It was the same fix on each of the attributes, you might want to change them around a little but it worked for me.  What I found was the in the newer versions of umbraco the custom attribute constructor was only being called once on application start.  So it worked for the very first language viewed but didnt have the ability to swap at any point.

I changed the location where it sets the errormessage and it all seemed to work.  Not all the attributes were affected but it did affect the main attributes.

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Brilliant thanks for this new PR @ccronin1974 I see the changes aot easier now & understand what you changed. Will accept & merge in now. I just need to find the time to build out a new NuGet package & update DLL version numbers later today

**Comment by warrenbuckley** [comment]
@craigacronin just out of curiosity did you try this without the jQuery.validation library. Do the error messages work in a full post back to the server?

**Comment by ccronin1974** [comment]
Classification:NOT PROTECTIVELY MARKED
No, sorry I can do?

I just ran the examples from your existing example package but can do further testing if you want?

**Comment by warrenbuckley** [comment]
@craigacronin no problem, if you have time that would be ace please!

Anyway great work & thank you for the contribution :+1:

**Pull request merged**
