### PR TITLE
Fixed issue with attributes not working in new version of Umbraco 7

### PR DESCRIPTION
**Pull request by craigacronin**
Hi Warren,

I have briefly gone through each attribute and all look like they are working.  I've also umbraco the example project so that it can be tested.

### CODE REVIEW

**Comment by warrenbuckley** [comment]
@ccronin1974 did you manage to find time to do a new PR that is a little easier to review?

**Comment by craigacronin** [comment]
Sorry warren

Since coming back into work today visual studio has been playing up and I've spent all morning on it.

I'm currently uninstalling and reinstalling the product.

Once I get this back up and running will do

**Comment by warrenbuckley** [comment]
@craigacronin sorry to hear that mate. Shall I close this PR in the meantime?

**Comment by craigacronin** [comment]
I have just jumped into vs2012

And creating it again.  Give me 20 mins

**Comment by craigacronin** [comment]
Think I've done it right?  So not used to contributing :)

**Pull request closed without merging**
